### PR TITLE
fix(build): add Tauri 2.11+ command name re-exports

### LINKED ISSUE #454: bug: Fresh clone fails to compile with Tauri 2.11+
## Description
A fresh `git clone` followed by `pnpm install && ./build-gpu.sh` fails to compile with 15 errors like:

```
error[E0433]: cannot find `__tauri_command_name_api_process_transcript` in `summary`
error[E0433]: cannot find `__tauri_command_name_api_get_summary` in `summary`
...
```

## Steps to Reproduce
1. `git clone https://github.com/Zackriya-Solutions/meeting-minutes`
2. `cd meeting-minutes/frontend`
3. `pnpm install`
4. `./build-gpu.sh`

## Expected Behavior
The project should compile successfully.

## Root Cause
`Cargo.lock` is in `.gitignore`, so fresh clones resolve Tauri to 2.11+ (since `Cargo.toml` specifies `"2.6.2"` which allows `>=2.6.2, <3.0.0`). Tauri 2.11 renamed the internal macro-generated items from `__cmd__` to `__tauri_command_name_`, but the re-exports in `summary/mod.rs` and `summary_engine/mod.rs` only include the `__cmd__` variants.

## Environment
- macOS (Apple Silicon)
- Rust 1.95.0 (Homebrew)
- pnpm 11.0.6

### PR DESCRIPTION
**Pull request by josepferrer**
## Description
Fresh clones fail to compile because `Cargo.lock` is gitignored and Cargo resolves Tauri to 2.11+, which renamed the internal macro-generated items from `__cmd__` to `__tauri_command_name_`. This PR adds both re-export variants so the build works with any Tauri 2.x version.

## Related Issue
Fixes #454

## Type of Change
- [x] Bug fix
- [ ] New feature
- [ ] Documentation update
- [ ] Performance improvement
- [ ] Code refactoring
- [ ] Other (please describe)

## Testing
- [ ] Unit tests added/updated
- [x] Manual testing performed
- [x] All tests pass

Verified by running `./build-gpu.sh` on a fresh clone (macOS, Apple Silicon). Build completes successfully producing `meetily.app` and `.dmg`.

## Documentation
- [x] No documentation needed

## Checklist
- [x] Code follows project style
- [x] Self-reviewed the code
- [x] Added comments for complex code
- [x] Updated README if needed

### CODE REVIEW

**Comment by safvanatzack** [comment]
Hi, thank you for your contribution @josepferrer .
This issue you noticed has already been fixed in a previous release by adding the lockfiles to the Git repository, so that the behavior become consistent. Because of this we will be deferring the PR.

Hope you can understand.
