### ISSUE TITLE
bug: Fresh clone fails to compile with Tauri 2.11+

### ISSUE THREAD

**Issue by josepferrer** [Zackriya-Solutions/meetily#454]
## Description
A fresh `git clone` followed by `pnpm install && ./build-gpu.sh` fails to compile with 15 errors like:

```
error[E0433]: cannot find `__tauri_command_name_api_process_transcript` in `summary`
error[E0433]: cannot find `__tauri_command_name_api_get_summary` in `summary`
...
```

## Steps to Reproduce
1. `git clone https://github.com/Zackriya-Solutions/meeting-minutes`
2. `cd meeting-minutes/frontend`
3. `pnpm install`
4. `./build-gpu.sh`

## Expected Behavior
The project should compile successfully.

## Root Cause
`Cargo.lock` is in `.gitignore`, so fresh clones resolve Tauri to 2.11+ (since `Cargo.toml` specifies `"2.6.2"` which allows `>=2.6.2, <3.0.0`). Tauri 2.11 renamed the internal macro-generated items from `__cmd__` to `__tauri_command_name_`, but the re-exports in `summary/mod.rs` and `summary_engine/mod.rs` only include the `__cmd__` variants.

## Environment
- macOS (Apple Silicon)
- Rust 1.95.0 (Homebrew)
- pnpm 11.0.6

**Comment by naganowl** [comment]
I ran into these same issues on Ubuntu 26.04 and I was able to get this to build successfully using #453
